export const constants = {
  HOST_NAME: process.env.REACT_APP_MAHJONG_HOST_NAME,
};

export const userStatus = {
  // User status
  OUT_ROOM: 'OUT_ROOM',
  IN_ROOM: 'IN_ROOM',
  IN_GAME: 'IN_GAME'
};

export const messageTypes = {
  // Pull message types
  PULL_ALL_ROOMS: 'PULL_ALL_ROOMS',
  PULL_ALL_USERS: 'PULL_ALL_USERS',
  PULL_CREATE_ROOM: 'PULL_CREATE_ROOM',
  PULL_JOIN_ROOM: 'PULL_JOIN_ROOM',

  PULL_ADD_BOT: 'PULL_ADD_BOT',
  PULL_REMOVE_BOT: 'PULL_REMOVE_BOT',
  PULL_START_GAME: 'PULL_START_GAME',

  PULL_EXIT_ROOM: 'PULL_EXIT_ROOM',


  // Push message types
  PUSH_USER_CONNECT: 'PUSH_USER_CONNECT',
  PUSH_USER_DISCONNECT: 'PUSH_USER_DISCONNECT',

  PUSH_ALL_ROOMS: 'PUSH_ALL_ROOMS',
  PUSH_ALL_USERS: 'PUSH_ALL_USERS',
  PUSH_CREATE_ROOM: 'PUSH_CREATE_ROOM',
  PUSH_JOIN_ROOM: 'PUSH_JOIN_ROOM',

  PUSH_ADD_BOT: 'PUSH_ADD_BOT',
  PUSH_REMOVE_BOT: 'PUSH_REMOVE_BOT',
  PUSH_START_GAME: 'PUSH_START_GAME',

  PUSH_EXIT_ROOM: 'PUSH_EXIT_ROOM',

  PUSH_INIT_GAME: 'PUSH_INIT_GAME',
};