export const constants = {
  HOST_NAME: process.env.REACT_APP_MAHJONG_HOST_NAME,
};

export const userStatus = {
  // User status
  OUT_ROOM: 'OUT_ROOM',
  IN_ROOM: 'IN_ROOM',
  IN_GAME: 'IN_GAME'
};

export const tileTypes = {
  // Tile sets
  SOUZU: 0, PINZU: 1, MANZU: 2, JIHAI: 3,

  // Tiles
  SOU_1: 0, SOU_2: 1, SOU_3: 2,
  SOU_4: 3, SOU_5: 4, SOU_6: 5,
  SOU_7: 6, SOU_8: 7, SOU_9: 8,
  PIN_1: 9, PIN_2: 10, PIN_3: 11,
  PIN_4: 12, PIN_5: 13, PIN_6: 14,
  PIN_7: 15, PIN_8: 16, PIN_9: 17,
  MAN_1: 18, MAN_2: 19, MAN_3: 20,
  MAN_4: 21, MAN_5: 22, MAN_6: 23,
  MAN_7: 24, MAN_8: 25, MAN_9: 26,
  TON: 27, NAN: 28, SHAA: 29, PEI: 30,
  HAKU: 31, HATSU: 32, CHUN: 33
};

export const messageTypes = {
  // Pull message types
  PULL_ALL_ROOMS: 'PULL_ALL_ROOMS',
  PULL_ALL_USERS: 'PULL_ALL_USERS',
  PULL_CREATE_ROOM: 'PULL_CREATE_ROOM',
  PULL_JOIN_ROOM: 'PULL_JOIN_ROOM',

  PULL_ADD_BOT: 'PULL_ADD_BOT',
  PULL_REMOVE_BOT: 'PULL_REMOVE_BOT',
  PULL_START_GAME: 'PULL_START_GAME',

  PULL_EXIT_ROOM: 'PULL_EXIT_ROOM',


  // Push message types
  PUSH_USER_CONNECT: 'PUSH_USER_CONNECT',
  PUSH_USER_DISCONNECT: 'PUSH_USER_DISCONNECT',

  PUSH_ALL_ROOMS: 'PUSH_ALL_ROOMS',
  PUSH_ALL_USERS: 'PUSH_ALL_USERS',
  PUSH_CREATE_ROOM: 'PUSH_CREATE_ROOM',
  PUSH_JOIN_ROOM: 'PUSH_JOIN_ROOM',

  PUSH_ADD_BOT: 'PUSH_ADD_BOT',
  PUSH_REMOVE_BOT: 'PUSH_REMOVE_BOT',
  PUSH_START_GAME: 'PUSH_START_GAME',

  PUSH_EXIT_ROOM: 'PUSH_EXIT_ROOM',

  PUSH_INIT_GAME: 'PUSH_INIT_GAME',
};